In [127]:
import numpy as np
import tensorflow as tf
import random as rn

np.random.seed(10)

rn.seed(10)

config = tf.ConfigProto(intra_op_parallelism_threads=1,
                              inter_op_parallelism_threads=1)

from keras import backend as K
tf.set_random_seed(10)
sess = tf.Session(graph=tf.get_default_graph(), config=config)
K.set_session(sess)

In [2]:
import pandas as pd

#0 1 2 3 4 5 
#2 3 4 5 6 8

#0 1 2 3
#2 3 4 9

In [11]:
flat_recall_results = []
flat_precision_results=[]
flat_accuracy_results=[]
flat_balanced_accuracy=[]
flat_f1_val=[]

stack_recall_results = []
stack_precision_results=[]
stack_accuracy_results=[]
stack_balanced_accuracy=[]
stack_f1_val=[]

base_recall_results = []
base_precision_results=[]
base_accuracy_results=[]
base_balanced_accuracy=[]
base_f1_val=[]

sub_recall_results = []
sub_precision_results=[]
sub_accuracy_results=[]
sub_balanced_accuracy=[]
sub_f1_val=[]



In [4]:
filtered_features_data = pd.read_csv("C:/kv/Thesus/Docs/filtered_features_data.csv",header=0)
filtered_features_data = filtered_features_data.loc[~filtered_features_data.sub_label.isin([2,8])]

print(np.unique(filtered_features_data.sub_label,return_counts=True))
print(np.unique(filtered_features_data.main_label,return_counts=True))

(array([3, 4, 5, 6], dtype=int64), array([ 226, 3166, 3583,  874], dtype=int64))
(array([3, 4, 9], dtype=int64), array([ 226, 3166, 4457], dtype=int64))


In [5]:
X = filtered_features_data[filtered_features_data.columns.difference(['source_id','sub_label','main_label'])]
#y_main = filtered_features_data.main_label
#y_sub = filtered_features_data.sub_label
y = filtered_features_data[['sub_label','main_label']]

In [6]:
del filtered_features_data
X=X.astype(float)


In [128]:
from keras.layers import Input,Dense,Dropout
from keras.models import Model,Sequential
from keras.initializers import glorot_normal,glorot_uniform
from keras.wrappers.scikit_learn import KerasClassifier
from keras.optimizers import Adam

def flat_model():
    
    model = Sequential()
    model.add(Dense(50, input_dim=42, activation='relu',kernel_initializer=glorot_normal(seed=100)))
    model.add(Dense(30,activation='relu'))

    model.add(Dense(4, activation='softmax'))
    optimizer=Adam(lr=0.001)
    # Compile model
    model.compile(loss='sparse_categorical_crossentropy',optimizer=optimizer, metrics=['sparse_categorical_accuracy'])#sparse_categorical_accuracy
    return model


def stack_model():
    #comes from flat
    model = Sequential()
    model.add(Dense(50, input_dim=46, activation='relu',kernel_initializer=glorot_normal(seed=100)))
    model.add(Dense(30,activation='relu'))

    model.add(Dense(4, activation='softmax'))
    optimizer=Adam(lr=0.001)
    # Compile model
    model.compile(loss='sparse_categorical_crossentropy',optimizer=optimizer, metrics=['sparse_categorical_accuracy'])#sparse_categorical_accuracy
    return model


def base_class_model():
    # create model
    model = Sequential()
    model.add(Dense(50, input_dim=42, activation='relu',kernel_initializer=glorot_normal(seed=100)))
    
    model.add(Dense(30,activation='relu'))
    
    model.add(Dense(3, activation='softmax'))
    optimizer=Adam(lr=0.001)
    # Compile model
    model.compile(loss='sparse_categorical_crossentropy',optimizer=optimizer, metrics=['sparse_categorical_accuracy'])#sparse_categorical_accuracy
    return model

def sub_class_model():
    model = Sequential()
    model.add(Dense(50, input_dim=45, activation='relu',kernel_initializer=glorot_normal(seed=100)))
    model.add(Dense(30,activation='relu'))

    model.add(Dense(4, activation='softmax'))
    optimizer=Adam(lr=0.001)
    # Compile model
    model.compile(loss='sparse_categorical_crossentropy',optimizer=optimizer, metrics=['sparse_categorical_accuracy'])#sparse_categorical_accuracy
    return model





def deep_flat_model():
    model = Sequential()
    model.add(Dense(50, input_dim=42, activation='relu',kernel_initializer=glorot_normal(seed=100)))
    model.add(Dense(45,activation='relu'))
    model.add(Dense(40,activation='relu'))
    model.add(Dense(35,activation='relu'))
    model.add(Dense(30,activation='relu'))
    model.add(Dense(25,activation='relu'))
    model.add(Dense(15,activation='relu'))
    model.add(Dense(10,activation='relu'))

    model.add(Dense(4, activation='softmax'))
    optimizer=Adam(lr=0.001)
    # Compile model
    
    model.compile(loss='sparse_categorical_crossentropy',optimizer=optimizer, metrics=['sparse_categorical_accuracy'])#sparse_categorical_accuracy
    return model

def deep_stack_model():
    model = Sequential()
    model.add(Dense(50, input_dim=46, activation='relu',kernel_initializer=glorot_normal(seed=100)))
    model.add(Dense(45,activation='relu'))
    model.add(Dense(40,activation='relu'))
    model.add(Dense(35,activation='relu'))
    model.add(Dense(30,activation='relu'))
    model.add(Dense(25,activation='relu'))
    model.add(Dense(15,activation='relu'))
    model.add(Dense(10,activation='relu'))

    model.add(Dense(4, activation='softmax'))
    optimizer=Adam(lr=0.001)
    # Compile model
    model.compile(loss='sparse_categorical_crossentropy',optimizer=optimizer, metrics=['sparse_categorical_accuracy'])#sparse_categorical_accuracy
    return model

def deep_base_model():
    model = Sequential()
    model.add(Dense(50, input_dim=42, activation='relu',kernel_initializer=glorot_normal(seed=100)))
    model.add(Dense(45,activation='relu'))
    model.add(Dense(40,activation='relu'))
    model.add(Dense(35,activation='relu'))
    model.add(Dense(30,activation='relu'))
    model.add(Dense(25,activation='relu'))
    model.add(Dense(15,activation='relu'))
    model.add(Dense(10,activation='relu'))

    model.add(Dense(3, activation='softmax'))
    optimizer=Adam(lr=0.001)
    # Compile model
    model.compile(loss='sparse_categorical_crossentropy',optimizer=optimizer, metrics=['sparse_categorical_accuracy'])#sparse_categorical_accuracy
    return model

def deep_sub_model():
    model = Sequential()
    model.add(Dense(50, input_dim=45, activation='relu',kernel_initializer=glorot_normal(seed=100)))
    model.add(Dense(45,activation='relu'))
    model.add(Dense(40,activation='relu'))
    model.add(Dense(35,activation='relu'))
    model.add(Dense(30,activation='relu'))
    model.add(Dense(25,activation='relu'))
    model.add(Dense(15,activation='relu'))
    model.add(Dense(10,activation='relu'))

    model.add(Dense(4, activation='softmax'))
    optimizer=Adam(lr=0.001)
    # Compile model
    model.compile(loss='sparse_categorical_crossentropy',optimizer=optimizer, metrics=['sparse_categorical_accuracy'])#sparse_categorical_accuracy
    return model




def getTrainTestData(X,y,random_seed):
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,random_state=random_seed)
    return X_train,X_test,y_train,y_test


def performScaling(X_train,X_test,y_train,y_test,col_list):

    from sklearn.preprocessing import RobustScaler, StandardScaler, MinMaxScaler
    scaler = RobustScaler()
    #scaler = MinMaxScaler()
    X_train_scl = scaler.fit_transform(X_train) #X_train #X_train_res
    X_test_scl = scaler.transform(X_test)

    X_train_scl = pd.DataFrame(X_train_scl, columns = col_list) #X-train_scl
    X_test_scl  = pd.DataFrame(X_test_scl, columns = col_list)

    y_train=y_train.reset_index(drop=True)
    y_test =y_test.reset_index(drop=True)

    scaled_train_df = pd.concat([X_train_scl,y_train],axis=1)
    scaled_test_df = pd.concat([X_test_scl,y_test],axis=1)
    
    #X_train_scl,X_test_scl,y_train,y_test
    return scaled_train_df,scaled_test_df

   

def getExperimentData(train_df,test_df,label_type):
    
    if (label_type=="base"):
        X_train = train_df[train_df.columns.difference(['sub_label','main_label'])]
        Y_train = train_df[['main_label']]

        X_test = test_df[test_df.columns.difference(['sub_label','main_label'])]
        Y_test = test_df[['main_label']]
    
    else:
        
        X_train = train_df[train_df.columns.difference(['sub_label','main_label'])]
        Y_train = train_df[['sub_label']]

        X_test = test_df[test_df.columns.difference(['sub_label','main_label'])]
        Y_test = test_df[['sub_label']]
    
    print("X_train:", X_train.shape)
    print("Y_train:", Y_train.shape)

    print("X_test", X_test.shape)
    print("Y_test", Y_test.shape)

    print("Y_train:", np.unique(Y_train,return_counts=True))
    print("Y_test:", np.unique( Y_test,return_counts=True))
    
    return X_train,X_test,Y_train,Y_test


def performSMOTE(X_train,X_test,y_train,y_test,col_list):
   

    print("Before OverSampling, counts of label '2': {}".format(sum(y_train.sub_label==2))) #sum(hy_train==0)
    print("Before OverSampling, counts of label '3': {}".format(sum(y_train.sub_label==3)))

    print("Before OverSampling, counts of label '4': {} \n".format(sum(y_train.sub_label==4)))
    print("Before OverSampling, counts of label '5': {} \n".format(sum(y_train.sub_label==5)))
    print("Before OverSampling, counts of label '6': {} \n".format(sum(y_train.sub_label==6)))
    print("Before OverSampling, counts of label '8': {} \n".format(sum(y_train.sub_label==8)))



    print("Applying SMOTE")

    from imblearn.over_sampling import SMOTE, ADASYN
    sm = SMOTE(random_state=2)
    X_train_res, y_train_res = sm.fit_sample(X_train, y_train.sub_label.ravel())

    #ad = ADASYN(sampling_strategy='auto',random_state=2)
    #X_train_res, y_train_res = ad.fit_resample(X_train, y_train.sub_label.ravel())

    print("After OverSampling, counts of label '2': {}".format(sum(y_train_res==2))) #sum(hy_train==0)
    
    print("After OverSampling, counts of label '3': {}".format(sum(y_train_res==3)))

    print("After OverSampling, counts of label '4': {} \n".format(sum(y_train_res==4)))
    print("After OverSampling, counts of label '5': {} \n".format(sum(y_train_res==5)))
    print("After OverSampling, counts of label '6': {} \n".format(sum(y_train_res==6)))
    print("After OverSampling, counts of label '8': {}".format(sum(y_train_res==8)))


    print(" train", np.unique(y_train_res,return_counts=True))
    
    X_train_res = pd.DataFrame(X_train_res, columns=col_list)
    y_train_res = pd.DataFrame(y_train_res, columns=['sub_label'])

    y_train_res['main_label']=y_train_res.sub_label
    
    
    #y_train_res.loc[y_train_res.sub_label==8,['main_label']]=2
    y_train_res.loc[y_train_res.sub_label==5,['main_label']]=9
    y_train_res.loc[y_train_res.sub_label==6,['main_label']]=9
    
    
    ##y_train_res=y_train_res.reset_index(drop=True)
    #y_test =y_test.reset_index(drop=True)

    smote_train_df = pd.concat([X_train_res,y_train_res],axis=1)
    smote_test_df = pd.concat([X_test,y_test],axis=1)
    
    #print(" test", np.unique(y_test,return_counts=True))

    return smote_train_df,smote_test_df

def get_weights(y_train):
    
    from sklearn.utils import class_weight
    class_weights = class_weight.compute_class_weight('balanced',
                                                     np.unique(y_train.main_label),
                                                     y_train.main_label)


    class_weight_dict = dict(enumerate(class_weights))

    return class_weight_dict
      

def get_estimator(model,X,y,weights):
    estimator = train_model(model,X,y)
    estimator.fit(X,y,class_weight=weights)
 
    return estimator

def train_model(base,X,y):
    
    from sklearn.model_selection import StratifiedKFold,cross_val_score  
    estimator = KerasClassifier(build_fn=base, epochs=300, batch_size=100,verbose=0)
   
        
    #kfold = StratifiedKFold(n_splits=10, shuffle=True,random_state=100)#random_state=0
    #results = cross_val_score(estimator,X,y, cv=kfold,scoring='balanced_accuracy')                              
    #print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))  
    print("skipped cv")
    return estimator

def evaluate_model(classifier,X,y):
   
    
    predictions,predict_prob,accuracy,bal_accuracy,precision,recall,f1,confusion_mat = get_metrics(classifier,X,y)
    
    print_metrics(accuracy,bal_accuracy,precision,recall,f1,confusion_mat)
    
    return predictions,predict_prob,accuracy,bal_accuracy,precision,recall,f1,confusion_mat

def get_metrics(classifier,X,y):
    
    from sklearn.metrics import accuracy_score,precision_score,recall_score,confusion_matrix,balanced_accuracy_score,f1_score
    predictions,predict_prob = get_predictions(classifier,X)
    accuracy = accuracy_score(y,predictions)
    balanced_accuracy= balanced_accuracy_score(y,predictions)
    precision=precision_score(y,predictions,average=None)
    recall = recall_score(y,predictions,average=None)
    confusion_mat = confusion_matrix(y,predictions)
    f1 = f1_score(y, predictions, labels=None, pos_label=1,average=None, sample_weight=None)
    
    return predictions,predict_prob,accuracy,balanced_accuracy,precision,recall,f1,confusion_mat

def get_predictions(classifier,X):
    return classifier.predict(X), classifier.predict_proba(X)


def print_metrics(accuracy,balanced_accuracy,precision,recall,f1,confusion_mat):    
    print(" Accuracy", accuracy)
    print(" Balanced accuracy",balanced_accuracy)
    print(" Recall",recall )
    print(" Precision",precision)
    print("f1",f1)
    print(confusion_mat)
    

def get_probs(dataset,predict_prob,method):
    if method=="stack":
        ip = pd.DataFrame(predict_prob, columns=['prob1','prob2','prob3','prob4'])
        X = dataset.copy()
        X['prob1']=ip[['prob1']]
        X['prob2']=ip[['prob2']]
        X['prob3']=ip[['prob3']]
        X['prob4']=ip[['prob4']]
        #X['prob5']=ip[['prob5']]
        #X['prob6']=ip[['prob6']]
        
    else:
        ip = pd.DataFrame(predict_prob, columns=['prob1','prob2','prob3'])
        X = dataset.copy()
        X['prob1']=ip[['prob1']]
        X['prob2']=ip[['prob2']]
        X['prob3']=ip[['prob3']]
        #X['prob4']=ip[['prob4']]

        
    return X



def put_in_df(metric,hierarchy):
    
    if(hierarchy=="accuracy"):
        headers=['accuracy','bal_accuracy']
    
    elif (hierarchy=="base"):
        headers = ['class3','class4','class9']
        
    else:
        headers= ['class3','class4','class5','class6']
    
    df = pd.DataFrame(metric,columns=headers)
    
    return df

def show_class_plots(X,y):
    classes = list(np.unique(y))
   
    from matplotlib import pyplot
    from numpy import where
    for class_value in classes:
        # select indices of points with the class label

        X_arr = np.asarray(X)


        row_ix = where(y == class_value)

        # scatter plot for points with a different color
        pyplot.scatter(X_arr[row_ix, 0], X_arr[row_ix, 1])
    # show plot
    pyplot.show()
    

In [ ]:
show_class_plots(X,y.sub_label)

In [129]:
feature_list=X.columns
X_train, X_test, y_train, y_test = getTrainTestData(X,y,100)



scaled_train_df, scaled_test_df = performScaling(X_train,X_test,y_train,y_test,feature_list)
#X_train_scl,X_test_scl,y_train_scl,y_test_scl = performScaling(X_train,X_test,y_train,y_test,feature_list)
#smote_train_df,smote_test_df = performSMOTE(X_train_scl,X_test_scl,y_train_scl,y_test_scl,feature_list)
flat_X_train,flat_X_test,flat_Y_train,flat_Y_test = getExperimentData(scaled_train_df, scaled_test_df,"flat")
base_X_train,base_X_test,base_Y_train,base_Y_test = getExperimentData(scaled_train_df, scaled_test_df,"base")
#sub_X_train,sub_X_test,sub_Y_train,sub_Y_test = getExperimentData(smote_train_df, smote_test_df,"sub")

#show_class_plots(flat_X_train,flat_Y_train.sub_label)
#show_class_plots(flat_X_test,flat_Y_test.sub_label)
del X_train,X_test,y_train,y_test
#X_train_scl,X_test_scl,y_train_scl,y_test_scl



X_train: (5886, 42)
Y_train: (5886, 1)
X_test (1963, 42)
Y_test (1963, 1)
Y_train: (array([3, 4, 5, 6], dtype=int64), array([ 174, 2370, 2698,  644], dtype=int64))
Y_test: (array([3, 4, 5, 6], dtype=int64), array([ 52, 796, 885, 230], dtype=int64))
X_train: (5886, 42)
Y_train: (5886, 1)
X_test (1963, 42)
Y_test (1963, 1)
Y_train: (array([3, 4, 9], dtype=int64), array([ 174, 2370, 3342], dtype=int64))
Y_test: (array([3, 4, 9], dtype=int64), array([  52,  796, 1115], dtype=int64))


In [130]:
weights={}

flat_estimator = get_estimator(deep_flat_model,flat_X_train,flat_Y_train,weights)
#base_estimator = get_estimator(base_class_model,base_X_train,base_Y_train,50,weights)

flat_train_predictions,flat_train_predict_prob = get_predictions(flat_estimator,flat_X_train)

flat_predictions,flat_predict_prob,flat_accuracy,flat_bal_accuracy,flat_precision,flat_recall,flat_f1,flat_confusion_mat=evaluate_model(flat_estimator,flat_X_test,flat_Y_test)

flat_recall_results.append(flat_recall)
flat_precision_results.append(flat_precision)
flat_accuracy_results.append([flat_accuracy,flat_bal_accuracy])
flat_f1_val.append(flat_f1)

skipped cv
 Accuracy 0.7809475292919001
 Balanced accuracy 0.626752252988769
 Recall [0.26923077 0.83291457 0.81355932 0.59130435]
 Precision [0.2295082  0.85218509 0.79034029 0.63849765]
f1 [0.24778761 0.84243964 0.80178174 0.61399549]
[[ 14   7  23   8]
 [  4 663 107  22]
 [ 33  85 720  47]
 [ 10  23  61 136]]


In [131]:


flat_accuracy_results
#flat_Y_test.head(1)

[[0.7936831380539989, 0.6107089911928621],
 [0.7901171676006113, 0.5968859587631381],
 [0.7758532857870606, 0.5969100325068255],
 [0.7931737137035151, 0.5988537723768925],
 [0.7865511971472237, 0.6285378609291342],
 [0.803871625063678, 0.630889019268915],
 [0.7992868059093224, 0.639376771131138],
 [0.8053998981151299, 0.6178574157029195],
 [0.7987773815588385, 0.6337710718286044],
 [0.7809475292919001, 0.626752252988769]]

In [ ]:
sub_X_test.head(1)

In [132]:
stack_X_train = get_probs(flat_X_train,flat_train_predict_prob,"stack")
stack_X_test = get_probs(flat_X_test,flat_predict_prob,"stack")

stack_Y_train= scaled_train_df[['sub_label']]
stack_Y_test = scaled_test_df[['sub_label']]

In [133]:
weights={}

stack_estimator = get_estimator(deep_stack_model,stack_X_train,stack_Y_train,weights)
#stack_estimator = get_estimator(stack_class_model,stack_X_train,stack_Y_train,50,weights)

stack_train_predictions,stack_train_predict_prob = get_predictions(stack_estimator,stack_X_train)

stack_predictions,stack_predict_prob,stack_accuracy,stack_bal_accuracy,stack_precision,stack_recall,stack_f1,stack_confusion_mat=evaluate_model(stack_estimator,stack_X_test,stack_Y_test)

stack_recall_results.append(stack_recall)
stack_precision_results.append(stack_precision)
stack_accuracy_results.append([stack_accuracy,stack_bal_accuracy])
stack_f1_val.append(stack_f1)

skipped cv
 Accuracy 0.8028527763627101
 Balanced accuracy 0.65493648708558
 Recall [0.32692308 0.86683417 0.8259887  0.6       ]
 Precision [0.28813559 0.87231353 0.81493868 0.63888889]
f1 [0.30630631 0.86956522 0.82042649 0.61883408]
[[ 17   6  21   8]
 [  3 690  82  21]
 [ 32  73 731  49]
 [  7  22  63 138]]


In [134]:
#stack_accuracy_results.pop()
#stack_precision_results.pop()

#stack_recall_results.pop()
#stack_f1_val.pop()
stack_accuracy_results

[[0.7906265919510953, 0.6067122705832383],
 [0.7885888945491595, 0.598882613637497],
 [0.7819663779928681, 0.5965179625991252],
 [0.7962302598064187, 0.6047500959494093],
 [0.7880794701986755, 0.6322236811227574],
 [0.8064187468160978, 0.6315552834295575],
 [0.8023433520122262, 0.633369575681977],
 [0.8099847172694855, 0.6261408238421003],
 [0.804381049414162, 0.6296572673295674],
 [0.8028527763627101, 0.65493648708558]]

In [135]:
#weights=get_weights(base_Y_train)
weights={}
base_estimator = get_estimator(deep_base_model,base_X_train,base_Y_train,weights)
#base_estimator = get_estimator(base_class_model,base_X_train,base_Y_train,50,weights)

base_train_predictions,base_train_predict_prob = get_predictions(base_estimator,base_X_train)

base_predictions,base_predict_prob,base_accuracy,base_bal_accuracy,base_precision,base_recall,base_f1,base_confusion_mat=evaluate_model(base_estimator,base_X_test,base_Y_test)

base_recall_results.append(base_recall)
base_precision_results.append(base_precision)
base_accuracy_results.append([base_accuracy,base_bal_accuracy])
base_f1_val.append(base_f1)

skipped cv
 Accuracy 0.8680590932246561
 Balanced accuracy 0.6339044018528887
 Recall [0.13461538 0.85678392 0.9103139 ]
 Precision [0.23333333 0.88686606 0.87199313]
f1 [0.17073171 0.8715655  0.89074155]
[[   7    6   39]
 [   4  682  110]
 [  19   81 1015]]


In [136]:
base_accuracy_results

[[0.8385124808965868, 0.6105678756022782],
 [0.8420784513499745, 0.6149600059750231],
 [0.8609271523178808, 0.664471865783007],
 [0.8588894549159449, 0.6487040010778734],
 [0.8644931227712684, 0.6548776279688263],
 [0.8604177279673968, 0.631741092021917],
 [0.8619460010188487, 0.6431456849775502],
 [0.8680590932246561, 0.6613465813020788],
 [0.8451349974528782, 0.6335100303660236],
 [0.8680590932246561, 0.6339044018528887]]

In [140]:

#base_accuracy_results.append([0.7834394904458599, 0.711897046524023])
#base_recall_results.pop()
#base_precision_results.pop()
#base_accuracy_results.pop()
#base_f1_val.pop()

In [137]:
sub_X_train = get_probs(base_X_train,base_train_predict_prob,"base")
sub_X_test = get_probs(base_X_test,base_predict_prob,"base")

sub_Y_train= scaled_train_df[['sub_label']]
sub_Y_test = scaled_test_df[['sub_label']]

print(sub_X_train.shape)
print(sub_X_test.shape)
print(np.unique(sub_Y_train,return_counts=True))
print(np.unique(sub_Y_test, return_counts=True))

(5886, 45)
(1963, 45)
(array([3, 4, 5, 6], dtype=int64), array([ 174, 2370, 2698,  644], dtype=int64))
(array([3, 4, 5, 6], dtype=int64), array([ 52, 796, 885, 230], dtype=int64))


In [59]:

#cols = sub_X_train.columns
#sub_X_train_scl,sub_X_test_scl,sub_Y_train_scl,sub_Y_test_scl = performScaling(sub_X_train,sub_X_test,sub_Y_train,sub_Y_test,cols)

In [138]:
weights={}

sub_estimator = get_estimator(deep_sub_model,sub_X_train,sub_Y_train,weights)
#sub_estimator = get_estimator(sub_class_model,sub_X_train,sub_Y_train,50,weights)

sub_train_predictions,sub_train_predict_prob = get_predictions(sub_estimator,sub_X_train)

sub_predictions,sub_predict_prob,sub_accuracy,sub_bal_accuracy,sub_precision,sub_recall,sub_f1,sub_confusion_mat=evaluate_model(sub_estimator,sub_X_test,sub_Y_test)

sub_recall_results.append(sub_recall)
sub_precision_results.append(sub_precision)
sub_accuracy_results.append([sub_accuracy,sub_bal_accuracy])
sub_f1_val.append(sub_f1)

skipped cv
 Accuracy 0.8099847172694855
 Balanced accuracy 0.6254851933837318
 Recall [0.13461538 0.8580402  0.8440678  0.66521739]
 Precision [0.19444444 0.88816645 0.81907895 0.62195122]
f1 [0.15909091 0.87284345 0.83138564 0.64285714]
[[  7   6  28  11]
 [  7 683  78  28]
 [ 17  67 747  54]
 [  5  13  59 153]]


In [139]:
sub_accuracy_results

[[0.7789098318899643, 0.5987921804050836],
 [0.7707590422822211, 0.5867156459919523],
 [0.7957208354559347, 0.6218542452484356],
 [0.7890983188996434, 0.6269803694589609],
 [0.8023433520122262, 0.6332964920759473],
 [0.8003056546102904, 0.6072328430670535],
 [0.7931737137035151, 0.5963449992535262],
 [0.804381049414162, 0.6205673526445326],
 [0.7911360163015793, 0.6071489129016926],
 [0.8099847172694855, 0.6254851933837318]]

In [156]:
#sub_recall_results.pop()
#sub_precision_results.pop()
#sub_accuracy_results.pop()
#sub_f1_val.pop()
#[[0.8166104553119731, 0.4302010414046331],
# [0.8204047217537943, 0.4361940189393212],
# [0.8204047217537943, 0.44585561851903416],
# [0.8182967959527825, 0.4570565603256556],
# [0.8166104553119731, 0.4599477653456745],
# [0.8182967959527825, 0.43322756627375325]]
#base_precision_results

In [140]:


base_precision_df=put_in_df(base_precision_results,"base")
base_recall_df=put_in_df(base_recall_results,"base")
base_f1_df=put_in_df(base_f1_val,"base")

sub_precision_df=put_in_df(sub_precision_results,"sub")
sub_recall_df=put_in_df(sub_recall_results,"sub")
sub_f1_df=put_in_df(sub_f1_val,"sub")


flat_precision_df=put_in_df(flat_precision_results,"flat")
flat_recall_df=put_in_df(flat_recall_results,"flat")
flat_f1_df=put_in_df(flat_f1_val,"flat")


stack_precision_df=put_in_df(stack_precision_results,"flat")
stack_recall_df=put_in_df(stack_recall_results,"flat")
stack_f1_df=put_in_df(stack_f1_val,"flat")


flat_acc_df = put_in_df(flat_accuracy_results,"accuracy")
stack_acc_df = put_in_df(stack_accuracy_results,"accuracy")
base_acc_df = put_in_df(base_accuracy_results,"accuracy")
sub_acc_df = put_in_df(sub_accuracy_results,"accuracy")


flat_precision_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_flat_precision.csv')
flat_recall_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_flat_recall.csv')
flat_f1_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_flat_f1.csv')

stack_precision_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_stack_precision.csv')
stack_recall_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_stack_recall.csv')
stack_f1_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_stack_f1.csv')


base_precision_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_base_precision.csv')
base_recall_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_base_recall.csv')
base_f1_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_base_f1.csv')


sub_precision_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_sub_precision.csv')
sub_recall_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_sub_recall.csv')
sub_f1_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_sub_f1.csv')



flat_acc_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_flat_acc.csv')
stack_acc_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_stack_acc.csv')
base_acc_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_base_acc.csv')
sub_acc_df.to_csv('C:/kv/Thesus/PLAStiCC/results/gaia/non_smote/deep_sub_acc.csv')




del stack_precision_df,stack_recall_df,stack_f1_df,flat_precision_df,flat_recall_df,flat_f1_df,base_precision_df,base_recall_df,base_f1_df,sub_precision_df,sub_recall_df,sub_f1_df
del flat_acc_df,stack_acc_df,base_acc_df,sub_acc_df

In [ ]:

#sub_precision_df=put_in_df(sub_precision_results,"sub")
#sub_recall_df=put_in_df(sub_recall_results,"sub")
#sub_f1_df=put_in_df(sub_f1_val,"sub")


#base_precision_df=put_in_df(base_precision_results,"base")
#base_recall_df=put_in_df(base_recall_results,"base")
#base_f1_df=put_in_df(base_f1_val,"base")


#flat_precision_df=put_in_df(flat_precision_results,"flat")
#flat_recall_df=put_in_df(flat_recall_results,"flat")
#flat_f1_df=put_in_df(flat_f1_val,"flat")


#stack_precision_df=put_in_df(stack_precision_results,"flat")
#stack_recall_df=put_in_df(stack_recall_results,"flat")
#stack_f1_df=put_in_df(stack_f1_val,"flat")

#flat_precision_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_flat_precision.csv')
#flat_recall_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_flat_recall.csv')
#flat_f1_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_flat_f1.csv')

#base_precision_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_base_precision.csv')
#base_recall_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_base_recall.csv')
#base_f1_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_base_f1.csv')


#sub_precision_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_sub_precision.csv')
#sub_recall_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_sub_recall.csv')
#sub_f1_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_sub_f1.csv')


#stack_precision_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_stack_precision.csv')
#stack_recall_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_stack_recall.csv')
#stack_f1_df.to_csv('C:/kv/Thesus/final_ops/tan_relu/tr_stack_f1.csv')


#del stack_precision_df,stack_recall_df,stack_f1_df,flat_precision_df,flat_recall_df,flat_f1_df,base_precision_df,base_recall_df,base_f1_df,sub_precision_df,sub_recall_df,sub_f1_df

In [ ]:

#[[0.8250421585160203, 0.41364078769907703]]
#[[0.877318718381113, 0.5038310200245086]]
#[[0.8284148397976391, 0.46965511621865424]]

#glorot_normal
#[[0.8136593591905565, 0.44069465626973914]]
#[[0.8756323777403036, 0.50548378051262]]
#[[0.8090219224283305, 0.4557164164824749]]

#glorot_uniform
#[[0.8237774030354131, 0.47176357587703527]]
#[[0.8722596964586846, 0.5088757120591351]]
#[[0.8043844856661045, 0.47038757225040745]]

#flat
#[[0.7995753715498939, 0.6365264017952621],
# [0.8220806794055202, 0.6356701349006082],
# [0.8169851380042463, 0.6268129529765984],
# [0.8292993630573249, 0.6395721852638229],
# [0.8199575371549894, 0.6453256436005167],
# [0.8229299363057325, 0.6588996873870432]]

#base
#[[0.8679405520169852, 0.6794615193036666],
# [0.8704883227176221, 0.6381314426462021],
# [0.8789808917197452, 0.6402200404682626],
# [0.8781316348195329, 0.6612129403493042],
# [0.8764331210191083, 0.6476376626659439],
# [0.8747346072186837, 0.6570557041839692]]

#[[0.8029723991507431, 0.6313469499778586],
# [0.8059447983014862, 0.6265881369849307],
# [0.8110403397027601, 0.6469963909939804],
# [0.8110403397027601, 0.6247791388573778],
#[0.8182590233545648, 0.626868811614477],
# [0.8110403397027601, 0.6382009224940102]]

In [ ]:
flat_accuracy_results

In [ ]:
base_accuracy_results

In [ ]:
sub_accuracy_results